### ISSUE TITLE
[Bug/Compatibility] Joining server message incorrect

### ISSUE THREAD

**Issue by voruti** [fooooooooooooooo/VelocityDiscord#11]
With the config line
```toml
[discord.chat]
join_message = "*{username} joined {server}*"
```
the wrong server is output in Discord. It shows the default server (lobby) instead of the server I'm actually joining.
I'm using this plugin to rejoin the last server I was connected to: https://github.com/Matt-MX/ReconnectVelocity
